@SmartSolarMicrogridAPI_HostAddress = http://localhost:5014

### API health check
GET {{SmartSolarMicrogridAPI_HostAddress}}/api/health
Accept: application/json

### Database connection check
GET {{SmartSolarMicrogridAPI_HostAddress}}/api/health/database
Accept: application/json
