name: API Build

on:
  push:
    branches: [main]
    paths:
      - 'SmartSolarMicrogridAPI/**'
  pull_request:
    branches: [main]
    paths:
      - 'SmartSolarMicrogridAPI/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore SmartSolarMicrogridAPI/SmartSolarMicrogridAPI.csproj

      - name: Build
        run: dotnet build SmartSolarMicrogridAPI/SmartSolarMicrogridAPI.csproj --no-restore --configuration Release
